FROM node:13.7-alpine as build
RUN npm install -g http-server
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --silent
COPY . /app
RUN npm run build

EXPOSE 3000

CMD ["http-server", "dist"]
